<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use App\Exceptions\Handler;
use Illuminate\Contracts\Debug\ExceptionHandler;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->disableExceptionHandling();
    }

    protected function signIn($user = null){
        $user = $user ?: create('App\User');

        $this->actingAs($user);

        return $this;
    }

    protected function disableExceptionHandling()
    {
        $this->oldExceptionHandler = app()->make(ExceptionHandler::class);

        app()->instance(Handler::class, new class extends Handler {
            public function __construct() {}
            public function report(Exception $e)
            {
                // no-op
            }
            public function render($request, Exception $e)
            {
                throw $e;
            }
        });
    }

}
